import { FC, ReactNode } from 'react'
import { Paper, Stack } from '@mui/material'
import { theme } from '../theme/theme'
import { AlexBreadCrumbs } from '../../shared-react-components/AlexBreadCrumbs/AlexBreadCrumbs.tsx'
import { autoGeneratedAllowedLinks } from '../config/routes-list-config.data.tsx'
import { alexBreadCrumbsNameMap } from '../config/alex-breadcrumbs-name-map.data.ts'

interface IProps {
    children?: ReactNode
}

export const PageWrapper: FC<IProps> = ({
                                            children,
                                        }) => (
    <Stack
        spacing={2}
        sx={{
            width: '100%',
            height: '100%',
            padding: theme.spacing(3),
            paddingBottom: 0,
            boxSizing: 'border-box',
        }}>
        <AlexBreadCrumbs nameMap={alexBreadCrumbsNameMap} allowedLinks={autoGeneratedAllowedLinks}/>
        <Paper
            elevation={2}
            sx={{
                height: '100%',
                overflow: 'hidden',
                borderRadius: '5px 5px 0 0',
            }}>
            {children}
        </Paper>
    </Stack>
)